import { makeFunctionReference } from "convex/server";

export const refs = {
  usersMe: makeFunctionReference<"query">("users:me"),
  ensureProfile: makeFunctionReference<"mutation">("users:ensureProfile"),
  updateSettings: makeFunctionReference<"mutation">("users:updateSettings"),
  jobsGet: makeFunctionReference<"query">("jobs:get"),
  jobsList: makeFunctionReference<"query">("jobs:list"),
  jobsRecent: makeFunctionReference<"query">("jobs:recent"),
  usageSnapshot: makeFunctionReference<"query">("usage:snapshot"),
  presetsList: makeFunctionReference<"query">("presets:list"),
  presetsSave: makeFunctionReference<"mutation">("presets:save"),
  adminOverview: makeFunctionReference<"query">("admin:overview"),
  adminListUsers: makeFunctionReference<"query">("admin:listUsers"),
  adminListJobs: makeFunctionReference<"query">("admin:listJobs"),
  adminListFlags: makeFunctionReference<"query">("admin:listFlags"),
  adminListHealth: makeFunctionReference<"query">("admin:listHealth"),
  adminClaimFirstAdmin: makeFunctionReference<"mutation">("admin:claimFirstAdmin"),
  adminSetUserRole: makeFunctionReference<"mutation">("admin:setUserRole"),
  adminSetUserPlan: makeFunctionReference<"mutation">("admin:setUserPlan"),
  adminSetUserDisabled: makeFunctionReference<"mutation">("admin:setUserDisabled"),
  adminCancelJob: makeFunctionReference<"mutation">("admin:cancelJob"),
  adminSetFlag: makeFunctionReference<"mutation">("admin:setFlag"),
  adminSeedFlags: makeFunctionReference<"mutation">("admin:seedFlags"),
};
