export const SAMPLES = [
  {
    id: "resolution-chart",
    title: "Fine detail",
    before: "/samples/chart-before.jpg",
    after: "/samples/chart-after.jpg",
    label: "preprocessed" as const,
    tool: "Image upscaler",
    note: "High-resolution Unsplash photo. The enhanced frame is a sharp master; the original is a downscaled, blurred preview — not a live model run.",
  },
  {
    id: "portrait-grain",
    title: "Grain and compression",
    before: "/samples/grain-before.jpg",
    after: "/samples/grain-after.jpg",
    label: "preprocessed" as const,
    tool: "Photo restoration",
    note: "Portrait from Unsplash. Enhanced is the clean master; original is a grainy JPEG simulation of the same frame.",
  },
  {
    id: "product-cutout",
    title: "Product cutout",
    before: "/samples/product-before.jpg",
    after: "/samples/product-after.jpg",
    label: "sample" as const,
    tool: "Background removal",
    note: "Product photo from Unsplash. Checkerboard indicates a demo cutout composite — not a live BiRefNet run.",
  },
  {
    id: "old-print",
    title: "Faded print",
    before: "/samples/print-before.jpg",
    after: "/samples/print-after.jpg",
    label: "preprocessed" as const,
    tool: "Color restoration",
    note: "Mountain scene from Unsplash. Faded original versus the full-color master of the same photograph.",
  },
  {
    id: "landscape",
    title: "Low-resolution landscape",
    before: "/samples/landscape-before.jpg",
    after: "/samples/landscape-after.jpg",
    label: "preprocessed" as const,
    tool: "Image upscaler",
    note: "Landscape from Unsplash at high resolution. Soft original versus the sharp master — labeled Preprocessed.",
  },
  {
    id: "document",
    title: "Document cleanup",
    before: "/samples/document-before.jpg",
    after: "/samples/document-after.jpg",
    label: "preprocessed" as const,
    tool: "Image cleanup",
    note: "Notebook photo from Unsplash. Stained/soft scan versus the clean master of the same page.",
  },
  {
    id: "video-frame",
    title: "Video frame",
    before: "/samples/video-before.jpg",
    after: "/samples/video-after.jpg",
    label: "sample" as const,
    tool: "Video sharpen",
    note: "Cinematic still from Unsplash standing in for video sharpen. Soft versus sharp — not a live encode.",
  },
] as const;
